version: '3.1'
services:
  app:
    container_name: springboot-postgresql
    command: >
      sh -c "/wait && java -jar /spring-boot-ecommerce.jar"
    image: springboot-postgresql
    extra_hosts:
      - 'postgresqldb:127.0.0.1'
    environment:
      - RP_DB_HOST=postgres
      - dbhost=localhost
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/ecommerce?autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useSSL=false
    build: ./
    ports:
      - '9090:8080'
    depends_on:
      - postgresqldb
  postgresqldb:
    container_name: postgresqldb
    image: 'postgres:13.1-alpine'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ecommerce
    expose:
      - 5432
    restart: always